In [1]:
# 1. Import the numpy package under the name np (★☆☆)


     
# 2. Print the numpy version and the configuration (★☆☆)


     
# 3. Create a null vector of size 10 (★☆☆)


     
# 4. How to find the memory size of any array (★☆☆)


     
# 5. How to get the documentation of the numpy add function from the command line? (★☆☆)


     
# 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)


     
# 7. Create a vector with values ranging from 10 to 49 (★☆☆)


     
# 8. Reverse a vector (first element becomes last) (★☆☆)


     
# 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

# 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
     

In [3]:
import numpy as np

In [7]:
print(np.__version__)
# np.show_config()

1.26.3


In [13]:
null_vector = np.zeros((10))
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [19]:
s = (null_vector.size * null_vector.itemsize)
s

80

In [23]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [25]:
arr = np.zeros((10))
arr[4] = 1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [28]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [29]:
z = np.arange(10,50,4)
print(z)
print(z[::-1])

[10 14 18 22 26 30 34 38 42 46]
[46 42 38 34 30 26 22 18 14 10]


In [30]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [35]:
n = np.array([1,2,0,0,4,0])
# worng
# for a in n:
#     if n[a] !=0:
#         print(a)
np.nonzero(n)

(array([0, 1, 4], dtype=int64),)

In [39]:
# np.identity(3)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# 11. Create a 3x3 identity matrix (★☆☆)


     
# 12. Create a 3x3x3 array with random values (★☆☆)


     
# 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)


     
# 14. Create a random vector of size 30 and find the mean value (★☆☆)


     
# 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

# 16. How to add a border (filled with 0's) around an existing array? (★☆☆)


     
# 17. What is the result of the following expression? (★☆☆)
# 0 * np.nan
# np.nan == np.nan
# np.inf > np.nan
# np.nan - np.nan
# np.nan in set([np.nan])
# 0.3 == 3 * 0.1


     
# 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)


     
# 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)


     
# 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [42]:
n = np.random.randint(1,50,27).reshape(3,3,3)
n

array([[[29, 26, 13],
        [36,  3, 23],
        [38, 13, 37]],

       [[43, 34, 18],
        [49, 32, 32],
        [17, 29, 21]],

       [[38, 14,  4],
        [13, 21, 34],
        [ 9, 12, 44]]])

In [43]:
n = np.random.randint(1,100,100).reshape(10,10)
print(n)
print(np.max(n))
print(np.min(n))

[[26 41  8 31 67 88 68  2 29 21]
 [99  8 44 19 49 36 69 42 28 25]
 [58  9 87 97  6 58 72 74 98 57]
 [87 87 26 54 79 76 14 30 53 28]
 [69 39 39 54 88 25 42 14 15 38]
 [ 9 16 36 94 32 49 97 21 52 66]
 [98 12 75 32 44 92 69 26 24 45]
 [87 57  3 53 46 10 92 72 25 58]
 [38 16 16 79  9 80 87 55 88 95]
 [50 80 12 75 32 20  7 60 85 85]]
99
2


In [45]:
np.random.random((10,10))

array([[0.22193738, 0.23280988, 0.5017774 , 0.34249482, 0.67879376,
        0.4381603 , 0.55258987, 0.6623442 , 0.23800211, 0.90984843],
       [0.95363052, 0.18955907, 0.21509063, 0.01652706, 0.2699997 ,
        0.63746535, 0.77163618, 0.19014495, 0.48354348, 0.34960143],
       [0.26126112, 0.84308689, 0.30251446, 0.94584051, 0.51160104,
        0.7426427 , 0.56004253, 0.89138711, 0.02713223, 0.96863857],
       [0.33289139, 0.69254457, 0.09579182, 0.13903546, 0.13247407,
        0.63076253, 0.91862631, 0.76775379, 0.93299186, 0.07147173],
       [0.55294978, 0.17815671, 0.42376367, 0.40017572, 0.2586061 ,
        0.42899663, 0.12294801, 0.87567788, 0.16280696, 0.48796467],
       [0.10972297, 0.77210651, 0.61341036, 0.98259706, 0.93588074,
        0.0336197 , 0.77947147, 0.27662506, 0.16313091, 0.94774371],
       [0.43965694, 0.06159952, 0.49562732, 0.03112217, 0.22666016,
        0.58191503, 0.76241939, 0.02259209, 0.62992764, 0.06800049],
       [0.98550506, 0.29647418, 0.7490289

In [46]:
n = np.random.random((6,5))
np.mean(n)

0.5812201057970245

In [48]:
n = np.ones((10,10))
n[1:9, 1:9] = 0
print(n)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [60]:
n = np.random.randint(1,10,100).reshape(10,10)
# n[0:1] = 0 so  on but
n = np.pad(n,pad_width=1, mode='constant', constant_values=0)
n

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 7, 8, 7, 7, 6, 5, 9, 1, 1, 0],
       [0, 5, 8, 6, 9, 4, 4, 5, 1, 3, 4, 0],
       [0, 7, 2, 6, 2, 7, 4, 5, 1, 8, 2, 0],
       [0, 1, 9, 5, 4, 2, 4, 6, 6, 5, 3, 0],
       [0, 7, 9, 8, 8, 4, 7, 1, 3, 5, 4, 0],
       [0, 2, 4, 7, 6, 9, 1, 9, 7, 7, 1, 0],
       [0, 3, 4, 5, 7, 5, 9, 2, 2, 4, 8, 0],
       [0, 7, 1, 7, 3, 8, 6, 9, 6, 7, 4, 0],
       [0, 5, 5, 6, 1, 3, 1, 3, 9, 4, 2, 0],
       [0, 9, 3, 9, 4, 3, 3, 4, 7, 5, 2, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [67]:
Z = np.ones((5,5))
Z[:, [0, -1]] = 0 #all row with 0 and last column
Z[[0, -1], :] = 0
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [71]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [77]:
n = np.diag(1+np.arange(4), k=1)
# n = np.diag(1+np.arange(3), k=1)
n
# z = np.arange(4) +1 


array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

In [91]:
z = np.zeros((8,8), dtype=int)
z[::2, ::2] = 1
z[1::2, 1::2] = 1
z

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [94]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [107]:
z = np.arange(1,6*7*8+1).reshape(6,7,8)
print(z[1,5,3])
print(z)
np.unravel_index(99,(6,7,8))


100
[[[  1   2   3   4   5   6   7   8]
  [  9  10  11  12  13  14  15  16]
  [ 17  18  19  20  21  22  23  24]
  [ 25  26  27  28  29  30  31  32]
  [ 33  34  35  36  37  38  39  40]
  [ 41  42  43  44  45  46  47  48]
  [ 49  50  51  52  53  54  55  56]]

 [[ 57  58  59  60  61  62  63  64]
  [ 65  66  67  68  69  70  71  72]
  [ 73  74  75  76  77  78  79  80]
  [ 81  82  83  84  85  86  87  88]
  [ 89  90  91  92  93  94  95  96]
  [ 97  98  99 100 101 102 103 104]
  [105 106 107 108 109 110 111 112]]

 [[113 114 115 116 117 118 119 120]
  [121 122 123 124 125 126 127 128]
  [129 130 131 132 133 134 135 136]
  [137 138 139 140 141 142 143 144]
  [145 146 147 148 149 150 151 152]
  [153 154 155 156 157 158 159 160]
  [161 162 163 164 165 166 167 168]]

 [[169 170 171 172 173 174 175 176]
  [177 178 179 180 181 182 183 184]
  [185 186 187 188 189 190 191 192]
  [193 194 195 196 197 198 199 200]
  [201 202 203 204 205 206 207 208]
  [209 210 211 212 213 214 215 216]
  [217 218 219 220

(1, 5, 3)

In [ ]:
# 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)


     
# 22. Normalize a 5x5 random matrix (★☆☆)


     
# 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)


     
# 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)


     
# 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)


     
# 26. What is the output of the following script? (★☆☆)
# # Author: Jake VanderPlas

# print(sum(range(5),-1))
# from numpy import *
# print(sum(range(5),-1))

# 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
# Z**Z
# 2 << Z >> 2
# Z <- Z
# 1j*Z
# Z/1/1
# Z<Z>Z


     
# 28. What are the result of the following expressions? (★☆☆)
# np.array(0) / np.array(0)
# np.array(0) // np.array(0)
# np.array([np.nan]).astype(int).astype(float)


     
# 29. How to round away from zero a float array ? (★☆☆)


     
# 30. How to find common values between two arrays? (★☆☆)

In [109]:
np.tile(np.array([[0,1],[1,0]]), (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [112]:
z = np.random.random((5,5))
z = (z-np.mean(z))/(np.std(z))
z

array([[ 1.06764984e+00,  1.77545555e+00, -9.98986921e-01,
        -3.64937219e-01, -1.28291929e+00],
       [ 1.12726756e+00,  3.05032720e-01,  1.14440683e+00,
        -9.75357909e-01, -1.53704910e-01],
       [ 1.30605471e+00, -1.03102231e+00, -1.15274221e+00,
         3.16675121e-04, -1.30324249e+00],
       [-1.11537487e+00, -5.81674469e-01, -8.27089907e-01,
        -2.25524338e-01, -3.12108130e-01],
       [ 1.33373350e+00,  1.65562246e+00,  2.18742116e-01,
        -6.49685667e-01,  1.04008868e+00]])

In [115]:
color = np.dtype([("r",np.ubyte),("g",np.ubyte),("b",np.ubyte),("a",np.ubyte)])

In [120]:
a = np.arange(15).reshape(5,3)
b = np.arange(6).reshape(3,2)
print(a)
print(b)
c = np.dot(a,b)
c

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[0 1]
 [2 3]
 [4 5]]


array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

In [121]:
a @ b

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

In [123]:
z = np.arange(10)
z[(3<z) & (z<8)] *= -1
z

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

In [127]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
# range(5) is treated as an array-like object: [0, 1, 2, 3, 4].
# The second argument -1 is interpreted as the axis parameter, not a starting value.

10
10


In [140]:
Z = np.arange(5)
print(Z)
# print(Z**Z)
# print(2 << Z >> 2)  first performs left shift then right shift
# print(Z <- Z) #erro it should be z < -z
# print(1j*Z) #comlex number represents root-1
print(Z/1/1)
# print(Z<Z>Z) #print((Z < Z) & (Z > Z))


[0 1 2 3 4]
[0. 1. 2. 3. 4.]


In [147]:
# np.array(0) / np.array(0)
# np.array(0) // np.array(0)
# np.array([np.nan]).astype(int).astype(float)

In [149]:

Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# rounded = np.where(arr > 0, np.ceil(arr), np.floor(arr))
# print(rounded)

[ 7.  5.  5. -4.  2. -3. -1.  6. -9. -5.]


In [153]:
Z1 = np.random.randint(0,10,10)

Z2 = np.random.randint(0,10,10)
print(Z1)
print(Z2)
print(np.intersect1d(Z1,Z2))

[8 6 4 9 6 6 2 3 5 8]
[7 0 8 8 7 3 6 4 4 2]
[2 3 4 6 8]


In [155]:
# 31. How to ignore all numpy warnings (not recommended)? (★☆☆)


     
# 32. Is the following expressions true? (★☆☆)
# np.sqrt(-1) == np.emath.sqrt(-1)


     
# 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)


     
# 34. How to get all the dates corresponding to the month of July 2016? (★★☆)


     
# 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
                                                            
# 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)


     
# 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)


     
# 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)


     
# 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)


     
# 40. Create a random vector of size 10 and sort it (★★☆)           

In [171]:
defaults = np.seterr(all="ignore")
# Z = np.ones(1) / 0
# a = np.array([1,3,4,0])
# a/0

In [168]:
np.sqrt(-1) == np.emath.sqrt(-1) 
# np.sqrt(-1) → nan with a warning.
# np.emath.sqrt(-1) → 1j (correct complex result).
# Comparison (==) → False.

False

In [173]:
_ = np.seterr(**defaults)


In [180]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday)
print(today)
print(tomorrow)

2025-02-05
2025-02-06
2025-02-07


In [182]:
Z = np.arange('2025-02', '2025-03', dtype='datetime64[D]')
print(Z)

['2025-02-01' '2025-02-02' '2025-02-03' '2025-02-04' '2025-02-05'
 '2025-02-06' '2025-02-07' '2025-02-08' '2025-02-09' '2025-02-10'
 '2025-02-11' '2025-02-12' '2025-02-13' '2025-02-14' '2025-02-15'
 '2025-02-16' '2025-02-17' '2025-02-18' '2025-02-19' '2025-02-20'
 '2025-02-21' '2025-02-22' '2025-02-23' '2025-02-24' '2025-02-25'
 '2025-02-26' '2025-02-27' '2025-02-28']


In [193]:
# ((A+B)*(-A/2))
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out = B)
np.divide(A,2,out = A)
np.negative(A,out=A)
np.multiply(A,B,out=A)
A

array([-1.5, -1.5, -1.5])

In [195]:
Z = np.random.uniform(0,10,10)
print(Z)
print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[8.74199631 4.22913321 2.75016362 0.40240413 2.27695528 6.78451954
 2.63941682 2.13787721 5.41469316 1.02616734]
[8. 4. 2. 0. 2. 6. 2. 2. 5. 1.]
[8. 4. 2. 0. 2. 6. 2. 2. 5. 1.]
[8. 4. 2. 0. 2. 6. 2. 2. 5. 1.]
[8 4 2 0 2 6 2 2 5 1]
[8. 4. 2. 0. 2. 6. 2. 2. 5. 1.]


In [196]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

# without broadcasting
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [203]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [207]:
v = np.linspace(0,1,11, endpoint=False)[1:]
v

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [211]:
np.random.randint(1,[3,5,9])

ValueError: low >= high